version: '3.1'
services:
  db:
    image: "postgres:15.4-alpine"
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - 5433:5432
    networks:
      - postgres
    volumes:
      - 'spring_postgres:/var/lib/postgresql/data/'

  musicreviewer:
    build: .
    depends_on:
      - db
    restart: on-failure
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - postgres

volumes:
  spring_postgres:
networks:
  postgres:
    driver: bridge
