version: '3.1'
services:
  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - elastic
    ports:
      - "2181:2181"

  kafka:
    image: 'confluentinc/cp-kafka:latest'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - elastic

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
#    container_name: elasticsearch
#    environment:
#      - node.name=elasticsearch
#      - discovery.type=single-node
#      - xpack.security.enabled=false
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - ES_JAVA_OPTS=-Xms1G -Xmx2G
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - esdata:/var/lib/elasticsearch/data
#    ports:
#      - "9200:9200"
#    networks:
#      - mailsender
#
#  kibana:
#    image: kibana:8.6.1
#    container_name: kibana
#    restart: on-failure
#    ports:
#      - "5601:5601"
#    depends_on:
#      - elasticsearch
#    networks:
#      - mailsender

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    environment: [ 'ES_JAVA_OPTS=-Xms1G -Xmx2G','bootstrap.memory_lock=true','discovery.type=single-node','xpack.security.enabled=false', 'xpack.security.enrollment.enabled=false' ]
    ports:
      - 9200:9200
    networks:
      - elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          cpus: '2.0'
        reservations:
          cpus: '1.0'

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    container_name: kibana
    environment:
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: d1a66dfd-c4d3-4a0a-8290-2abcb83ab3aa
    ports:
      - 5601:5601
    networks:
      - elastic
    deploy:
      resources:
        limits:
          cpus: '2.0'
        reservations:
          cpus: '1.0'

  mailsender:
    build: .
    restart: on-failure
    depends_on:
      - kafka
      - elasticsearch
    ports:
      - "8080:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#      ELASTICSEARCH_ADDRESS: elasticsearch:9200
      SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES: elasticsearch:9200
      SPRING_DATA_ELASTICSEARCH_CLUSTER_NAME: elasticsearch
      SPRING_DATA_ELASTICSEARCH_REPOSITORIES_ENABLED: true
      SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200
    networks:
      - elastic

volumes:
  esdata:
#    driver: local
networks:
  mailsender:
  elastic:
